# Generated by Django 6.0.4 on 2026-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='nrc_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='transcript_url',
        ),
        migrations.AddField(
            model_name='application',
            name='nrc',
            field=models.FileField(blank=True, null=True, upload_to='documents/nrc/'),
        ),
        migrations.AddField(
            model_name='application',
            name='other',
            field=models.FileField(blank=True, null=True, upload_to='documents/others/'),
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/transcripts/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
